export const GET_MOVIES = "GET_MOVIES";
export const ADD_MOVIE_FAVORITE = 'ADD_MOVIE_FAVORITE';
export const GET_MOVIES_DATAIL = 'GET_MOVIES_DATAIL'
export const REMOVE_MOVIE = 'REMOVE_MOVIE_FAVORITE'